routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\AdjustmentController;
use App\Http\Controllers\Web\DeliveryOrderController;
use App\Http\Controllers\Web\DeliveryScheduleController;
use App\Http\Controllers\Web\FormController;
use App\Http\Controllers\Web\FormulaController;
use App\Http\Controllers\Web\HistoryController;
use App\Http\Controllers\Web\JobCostController;
use App\Http\Controllers\Web\LoginController;
use App\Http\Controllers\Web\MachineCategoryController;
use App\Http\Controllers\Web\MachineController;
use App\Http\Controllers\Web\MachineProcessTypeController;
use App\Http\Controllers\Web\RelationController;
use App\Http\Controllers\Web\MaterialReleaseController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\ProductionOrderController;
use App\Http\Controllers\Web\SalesOrderController;
use App\Http\Controllers\Web\ProductResultController;
use App\Http\Controllers\Web\ReceiveItemController;
use App\Http\Controllers\Web\RoleController;
use App\Http\Controllers\Web\ScheduleController;
use App\Http\Controllers\Web\StocktakingController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Web\WarehouseController;
use App\Http\Controllers\Web\WarehouseRackController;
use App\Http\Controllers\Web\WorkOrderController;
use App\Http\Controllers\Api\ApiScheduleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route for user login
Route::get('/login', [LoginController::class, 'view'])->name('login');
Route::post('/login', [LoginController::class, 'attempt'])->name('attemptLogin');
Route::get('/logout', [LoginController::class, 'logout'])->middleware('auth')->name('logout');

// Routes inside middleware 'auth' require authentication
Route::middleware('auth')->group(function () {

    // Home route
    Route::view('/', 'pages.home')->name('home');

    Route::get('/schedule/production/ongoing', [ApiScheduleController::class, 'loadProductionOngoing'])->name('plan.production.ongoing');

    // Route for viewing product history
    Route::get('/products/{product}/history', [HistoryController::class, 'index']);

    // Resource routes for various controllers
    Route::resource('/adjustments', AdjustmentController::class);
    Route::resource('/deliveries', DeliveryOrderController::class);
    Route::resource('/formulas', FormulaController::class);
    Route::resource('/jobcosts', JobCostController::class);
    Route::resource('/machines', MachineController::class);
    Route::resource('/machine-category', MachineCategoryController::class);
    Route::resource('/machine-process-type', MachineProcessTypeController::class);
    Route::resource('/products', ProductController::class);
    Route::resource('/receives', ReceiveItemController::class);
    Route::resource('/relations', RelationController::class);
    Route::resource('/results', ProductResultController::class);
    Route::resource('/roles', RoleController::class);
    Route::resource('/users', UserController::class);
    Route::resource('/warehouses', WarehouseController::class);
    Route::resource('/warehouses.racks', WarehouseRackController::class);

    // Custom route for rendering work order form
    Route::get('/form/work-order/{formula}', [FormController::class, 'renderWorkOrderForm']);
    Route::get('/form/material-release/{lotNumber}', [FormController::class, 'renderMaterialReleaseForm']);
    Route::get('/form/production-result/{lotNumber}', [FormController::class, 'renderProductionResultForm']);

    // Route for exporting stocktaking data
    Route::get('/stocktaking/export', [StocktakingController::class, 'cutOff'])->name('stocktaking.export');
    Route::resource('/warehouses.racks', WarehouseRackController::class);

    // Route for viewing production schedule
    Route::get('/schedule/production', [ScheduleController::class, 'production'])->name("plan.production");
    Route::get('/schedule/production/preview', [ScheduleController::class, 'previewproduction'])->name("plan.production.preview");


    Route::get('/schedule/delivery', [ScheduleController::class, 'delivery'])->name("plan.delivery");

    Route::resource('salesorder', SalesOrderController::class)
        ->parameters(['salesorder' => 'order'])->except(['destroy', 'show']);

    Route::resource('productionorder', ProductionOrderController::class)
        ->parameters(['productionorder' => 'order'])->except(['create', 'update', 'destroy', 'show']);

    Route::get('productionorder/create/{product}', [ProductionOrderController::class, 'create'])
        ->name('productionorder.create');

    Route::put('productionorder/{product}', [ProductionOrderController::class, 'update'])
        ->name('productionorder.update');

    Route::resource('deliveryrequest', DeliveryScheduleController::class)->except('destroy', 'show');

    Route::resource('/workorders', WorkOrderController::class);

    Route::view('/warehouse-release', 'pages.material-release.material-release-form-warehouse');
    Route::resource('/releases', MaterialReleaseController::class);
});

app/View/Components/Layouts/BaseCardComponent.php
<?php

namespace App\View\Components\Layouts;

use Illuminate\View\Component;

class BaseCardComponent extends Component
{
    /**
     * The theme mode for the card (full or outline).
     *
     * @var string
     */
    public $themeMode;

    /**
     * The theme color for the card.
     *
     * @var string
     */
    public $theme;

    /**
     * The CSS class for the card body.
     *
     * @var string
     */
    public $bodyClass;

    /**
     * The custom component to be displayed inside the card body.
     *
     * @var mixed
     */
    public $dynamicComponent;

    /**
     * The title for the card header.
     *
     * @var string|null
     */
    public $cardTitle;

    /**
     * Whether or not the card is collapsible.
     *
     * @var string|null
     */
    public $cardCollapsible;

    public function __construct($cardTitle = null, $themeMode = 'outline', $theme = 'primary', $dynamicComponent = null, $bodyClass = 'p-3', $cardCollapsible = null)
    {
        $this->themeMode = $themeMode;
        $this->theme = $theme;
        $this->cardTitle = $cardTitle;
        $this->cardCollapsible = $cardCollapsible;
        $this->bodyClass = $bodyClass;
        $this->dynamicComponent = $dynamicComponent;
    }

    /**
     * Generate the CSS class for the card based on its properties.
     *
     * @return string The CSS class for the card.
     */
    public function cardClass()
    {
        $classes = ['card'];

        // Add theme-related classes.
        if (isset($this->theme)) {
            $base = $this->themeMode === 'full' ? 'bg' : 'card';
            $classes[] = "{$base}-{$this->theme}";

            if ($this->themeMode === 'outline') {
                $classes[] = 'card-outline';
            }
        }

        // Add collapsible-related classes.
        if ($this->cardCollapsible === 'collapsed') {
            $classes[] = 'collapsed-card';
        }

        // Return the concatenated string of classes.
        return implode(' ', $classes);
    }

    /**
     * Generate the CSS class for the card body based on its properties.
     *
     * @return string The CSS class for the card body.
     */
    public function cardBodyClass()
    {
        $classes = ['card-body'];

        if (isset($this->bodyClass)) {
            $classes[] = $this->bodyClass;
        }

        // Return the concatenated string of classes.
        return implode(' ', $classes);
    }

    /**
     * Check if the card has any tools (e.g. collapsible button).
     *
     * @return bool Whether or not the card has any tools.
     */
    public function hasCardTools()
    {
        return isset($this->cardCollapsible);
    }

    /**
     * Render the BaseCardComponent view.
     *
     * @return \Illuminate\Contracts\View\View The rendered view.
     */
    public function render()
    {
        return view('components.layouts.base-card-component');
    }
}

app/View/Components/Layouts/BaseFormComponent.php
<?php

namespace App\View\Components\Layouts;

use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\View\Component;

/**
 * Class BaseFormComponent
 * @package App\View\Components\Layouts
 *
 * A reusable component for creating and updating forms
 */
class BaseFormComponent extends Component
{
    /**
     * The title of the form
     * @var string
     */
    public string $title;

    /**
     * The keys of the route
     * @var array
     */
    public array $routeKeys;

    /**
     * The prefix of the route
     * @var string
     */
    public string $routePrefix;

    /**
     * The model to be updated, if any
     * @var object|null
     */
    public ?object $model = null;

    /**
     * The parameters for the route
     * @var array
     */
    public array $param;

    /**
     * BaseFormComponent constructor.
     * @param string $title The title of the form
     * @param string $routePrefix The prefix of the route
     * @param mixed|null $param The parameters for the route, if any
     */
    public function __construct(string $title, string $routePrefix, $key = null, $param = null)
    {
        $this->title = $title;
        $this->routePrefix = $routePrefix;
        $this->param = Arr::wrap($param);

        // Split the route prefix into an array of keys
        $this->routeKeys = collect(explode('.', str_replace('-', '_', $key ?? $routePrefix)))->map(fn ($key) => Str::singular($key))->toArray();

        // The last parameter is assumed to be the model (if any)
        $this->model = Arr::last($this->param);
    }

    /**
     * Returns the title of the form with "Create" or "Update" appended, depending on whether a model is present
     * @return string
     */
    public function getTitle(): string
    {
        return count($this->routeKeys) == count($this->param) ? "{$this->title} Update" : "{$this->title} Create";
    }

    /**
     * Returns the URL for the form submission, with any parameters included
     * @return string
     */
    public function getRoute(): string
    {
        $param = [];

        // Map the route keys to the corresponding parameter IDs
        $param = collect($this->param)->mapWithKeys(function ($param, $index) {
            return [$this->routeKeys[$index] => $param['id']];
        })->toArray();

        // Return the URL with the appropriate action ("store" for create, "update" for update)
        return route("{$this->routePrefix}." . (count($this->routeKeys) == count($param) ? 'update' : 'store'), $param);
    }

    /**
     * Returns the HTTP method for the form submission (either "POST" or "PUT")
     * @return string
     */
    public function getMethod(): string
    {
        return count($this->routeKeys) == count($this->param) ? 'PUT' : 'POST';
    }

    /**
     * Render method that returns the view to be rendered
     * @return \Illuminate\Contracts\View\View
     */
    public function render()
    {
        return view('components.layouts.base-form-component');
    }
}

app/View/Components/Layouts/BaseTableComponent.php
<?php

namespace App\View\Components\Layouts;

use Illuminate\View\Component;

class BaseTableComponent extends Component
{
    /**
     * The array of columns to be displayed in the table.
     *
     * @var array
     */
    public $columns;

    /**
     * Create a new component instance.
     *
     * @param array $columns The columns to be displayed in the table.
     * @return void
     */
    public function __construct($columns = [])
    {
        $this->columns = $columns;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.layouts.base-table-component');
    }
}

app/View/Components/Layouts/SidebarMenu.php
<?php

namespace App\View\Components\Layouts;

use Illuminate\View\Component;

class SidebarMenu extends Component
{
    /**
     * The URL to redirect to
     *
     * @var string
     */
    public string $url;

    /**
     * The icon to display for the menu item
     *
     * @var string
     */
    public string $icon;

    /**
     * The label to display for the menu item
     *
     * @var string
     */
    public string $label;

    /**
     * The permission required to view this menu item
     *
     * @var string|null
     */
    public ?string $permission;

    /**
     * The current URL, cached in the constructor
     *
     * @var string|null
     */
    private string $currentUrl;

    /**
     * Create a new component instance.
     *
     * @param string $label The label to display for the menu item
     * @param string $url The URL to redirect to
     * @param string $icon The icon to display for the menu item
     * @return void
     */
    public function __construct($label = 'Menu', string $url = '#', string $icon = 'fas fa-circle nav-icon', string $permission = null)
    {
        $this->label        = $label;
        $this->icon         = $icon;
        $this->url          = $url;
        $this->permission   = $permission;

        $this->currentUrl = url()->current();
    }

    /**
     * Get if this sidebar menu item is active
     */
    public function isActive(): string
    {
        return $this->url === $this->currentUrl ? 'active' : '';
    }

    /**
     * Get if the current user has permission to view this menu item
     */
    public function hasPermission(): bool
    {
        return $this->permission ? auth()->user()->hasPermissionTo($this->permission) : true;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return $this->hasPermission() ? view('components.layouts.sidebar-menu') : '';
    }
}

resources/views/_layouts/base.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@yield('title')</title>

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    @yield('css')
    @stack('css')

    <!-- AdminLTE App -->
    <link rel="stylesheet" href="{{ URL::asset('css/app.css') }}">

    <style>
        /* Chrome, Safari, Edge, Opera */
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        /* Firefox */
        input[type=number] {
            -moz-appearance: textfield;
        }
    </style>
</head>

<body class="hold-transition sidebar-mini sidebar-collapse">
    <div class="wrapper">

        @include('_layouts.navbar')
        @include('_layouts.sidebar')

        <div class="content-wrapper">
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1>@yield('header-content')</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                @yield('breadcumb')
                            </ol>
                        </div>
                    </div>
            </section>

            <!-- Main content -->
            <section class="content">
                @yield('content')
            </section>
            <!-- /.content -->
        </div>

        @include('_layouts.footer')

        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
    </div>

    <!-- AdminLTE App -->
    <script src="{{ URL::asset('js/app.js') }}"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @include('sweetalert::alert')

    @yield('js')
    @stack('js')
</body>

</html>

resources/views/_layouts/footer.blade.php
<footer class="main-footer no-print">
<div class="float-right d-none d-sm-block">
  <b>Version</b> 1.0.0
</div>
<strong>Copyright &copy; 2020 <a href="#">PT. Focus Color Indonesia</a>.</strong> All rights reserved.
</footer>

resources/views/_layouts/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
</nav>

resources/views/_layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="#" class="brand-link">
        <img src="#" alt="" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">FOCSystem</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src='https://ui-avatars.com/api/?name={{ Auth::user()->username }}&background=0D8ABC&color=fff'
                    class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ Auth::user()->username }}</a>
                @foreach (Auth::user()->roles as $role)
                    <span class="text-muted">{{ ucwords($role->name) }}</span>
                @endforeach
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <x-sidebar-menu label='Home' :url="route('home')" icon='fas fa-home' />

                @can('view laboratory')
                    <li class="nav-header">LABORATORY</li>
                    <x-sidebar-menu label='Formula' :url="route('formulas.index')" icon='fas fa-flask' />
                @endcan

                @can('view marketing')
                    <li class="nav-header">MARKETING</li>
                    <x-sidebar-menu label='Sales Order (SO)' :url="route('salesorder.index')" icon='fas fa-clipboard-list' />
                @endcan

                @can('view ppic')
                    <li class="nav-header">PPIC</li>
                    <x-sidebar-menu label='Production Order' :url="route('productionorder.index')" icon='fas fa-clipboard-list' />
                    <x-sidebar-menu label='Production Planning' :url="route('plan.production')" icon='fas fa-calendar-alt' />
                @endcan

                @can('view manufacture')
                    <li class="nav-header">MANUFACTURE</li>
                    <x-sidebar-menu label='Work Order (WO)' :url="route('workorders.index')" icon='fas fa-clipboard-list' />
                    <x-sidebar-menu label='Release Material' :url="route('releases.index')" icon='fas fa-box-open' />
                    <x-sidebar-menu label='Product Result' :url="route('results.index')" icon='fas fa-box' />
                    <x-sidebar-menu label='Job Cost' :url="route('jobcosts.index')" icon='fas fa-drafting-compass' />
                @endcan

                @can('view warehouse')
                    <li class="nav-header">WAREHOUSE</li>
                    <x-sidebar-menu label='Receive item' :url="route('receives.index')" icon='fas fa-truck-loading' />
                    {{-- <x-sidebar-menu label='Delivery Request' :url="route('deliveryrequest.index')" icon='fas fa-clipboard-list' />
                    <x-sidebar-menu label='Delivery Planning' :url="route('plan.delivery')" icon='fas fa-calendar-alt' /> --}}
                    <x-sidebar-menu label='Delivery Order' :url="route('deliveries.index')" icon='fas fa-truck' />
                    <x-sidebar-menu label='Adjustment' :url="route('adjustments.index')" icon='fas fa-pencil-ruler' />
                @endcan

                <li class="nav-header"></li>
                <x-sidebar-menu label='Product' :url="route('products.index')" icon='fas fa-boxes' />

                @can('view administration')
                    <li class="nav-header">ADMINISTRATION</li>
                    <x-sidebar-menu label='Users Management' :url="route('users.index')" icon='fas fa-users' />
                    <x-sidebar-menu label='Roles Management' :url="route('roles.index')" icon='fas fa-user-tag' />
                @endcan

                <li class="nav-header">DATA MASTER</li>
                <x-sidebar-menu label='Data Machine' :url="route('machines.index')" icon='far fa-circle' />
                <x-sidebar-menu label='Data Machine Process Type' :url="route('machine-process-type.index')" icon='far fa-circle' />
                <x-sidebar-menu label='Warehouse' :url="route('warehouses.index')" icon='far fa-circle' />
                <x-sidebar-menu label='Relation Company' :url="route('relations.index')" icon='far fa-circle' />

                <li class="nav-header">PROFILE</li>
                <x-sidebar-menu label='Logout' :url="route('logout')" icon='fas fa-sign-out-alt' />

            </ul>
        </nav>
    </div>
</aside>