routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\AdjustmentController;
use App\Http\Controllers\Web\DeliveryOrderController;
use App\Http\Controllers\Web\DeliveryScheduleController;
use App\Http\Controllers\Web\FormController;
use App\Http\Controllers\Web\FormulaController;
use App\Http\Controllers\Web\HistoryController;
use App\Http\Controllers\Web\JobCostController;
use App\Http\Controllers\Web\LoginController;
use App\Http\Controllers\Web\MachineCategoryController;
use App\Http\Controllers\Web\MachineController;
use App\Http\Controllers\Web\MachineProcessTypeController;
use App\Http\Controllers\Web\RelationController;
use App\Http\Controllers\Web\MaterialReleaseController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\ProductionOrderController;
use App\Http\Controllers\Web\SalesOrderController;
use App\Http\Controllers\Web\ProductResultController;
use App\Http\Controllers\Web\ReceiveItemController;
use App\Http\Controllers\Web\RoleController;
use App\Http\Controllers\Web\ScheduleController;
use App\Http\Controllers\Web\StocktakingController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Web\WarehouseController;
use App\Http\Controllers\Web\WarehouseRackController;
use App\Http\Controllers\Web\WorkOrderController;
use App\Http\Controllers\Api\ApiScheduleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route for user login
Route::get('/login', [LoginController::class, 'view'])->name('login');
Route::post('/login', [LoginController::class, 'attempt'])->name('attemptLogin');
Route::get('/logout', [LoginController::class, 'logout'])->middleware('auth')->name('logout');

// Routes inside middleware 'auth' require authentication
Route::middleware('auth')->group(function () {

    // Home route
    Route::view('/', 'pages.home')->name('home');

    Route::get('/schedule/production/ongoing', [ApiScheduleController::class, 'loadProductionOngoing'])->name('plan.production.ongoing');

    // Route for viewing product history
    Route::get('/products/{product}/history', [HistoryController::class, 'index']);

    // Resource routes for various controllers
    Route::resource('/adjustments', AdjustmentController::class);
    Route::resource('/deliveries', DeliveryOrderController::class);
    Route::resource('/formulas', FormulaController::class);
    Route::resource('/jobcosts', JobCostController::class);
    Route::resource('/machines', MachineController::class);
    Route::resource('/machine-category', MachineCategoryController::class);
    Route::resource('/machine-process-type', MachineProcessTypeController::class);
    Route::resource('/products', ProductController::class);
    Route::resource('/receives', ReceiveItemController::class);
    Route::resource('/relations', RelationController::class);
    Route::resource('/results', ProductResultController::class);
    Route::resource('/roles', RoleController::class);
    Route::resource('/users', UserController::class);
    Route::resource('/warehouses', WarehouseController::class);
    Route::resource('/warehouses.racks', WarehouseRackController::class);

    // Custom route for rendering work order form
    Route::get('/form/work-order/{formula}', [FormController::class, 'renderWorkOrderForm']);
    Route::get('/form/material-release/{lotNumber}', [FormController::class, 'renderMaterialReleaseForm']);
    Route::get('/form/production-result/{lotNumber}', [FormController::class, 'renderProductionResultForm']);

    // Route for exporting stocktaking data
    Route::get('/stocktaking/export', [StocktakingController::class, 'cutOff'])->name('stocktaking.export');
    Route::resource('/warehouses.racks', WarehouseRackController::class);

    // Route for viewing production schedule
    Route::get('/schedule/production', [ScheduleController::class, 'production'])->name("plan.production");
    Route::get('/schedule/production/preview', [ScheduleController::class, 'previewproduction'])->name("plan.production.preview");


    Route::get('/schedule/delivery', [ScheduleController::class, 'delivery'])->name("plan.delivery");

    Route::resource('salesorder', SalesOrderController::class)
        ->parameters(['salesorder' => 'order'])->except(['destroy', 'show']);

    Route::resource('productionorder', ProductionOrderController::class)
        ->parameters(['productionorder' => 'order'])->except(['create', 'update', 'destroy', 'show']);

    Route::get('productionorder/create/{product}', [ProductionOrderController::class, 'create'])
        ->name('productionorder.create');

    Route::put('productionorder/{product}', [ProductionOrderController::class, 'update'])
        ->name('productionorder.update');

    Route::resource('deliveryrequest', DeliveryScheduleController::class)->except('destroy', 'show');

    Route::resource('/workorders', WorkOrderController::class);

    Route::view('/warehouse-release', 'pages.material-release.material-release-form-warehouse');
    Route::resource('/releases', MaterialReleaseController::class);
});

app/Models/Relation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Relation extends Model
{
    use HasFactory;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * Define a one-to-many relationship with the DeliveryOrder model.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function delivery()
    {
        return $this->hasMany(DeliveryOrder::class, 'description');
    }

    /**
     * Define a one-to-many relationship with the ReceiveItem model.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function receive()
    {
        return $this->hasMany(ReceiveItem::class, 'description');
    }
}

app/Http/Controllers/Web/RelationController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\RelationRequest;
use App\Models\Relation;

class RelationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.relations.relation-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.relations.relation-form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RelationRequest $request)
    {
        Relation::create($request->validated());

        return redirect()
            ->intended(route('relations.index'))
            ->with('toast_success', "Created <b>'{$request->name}'</b>, Successfully!");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Relation $relation
     * @return \Illuminate\Http\Response
     */
    public function edit(Relation $relation)
    {
        return view('pages.relations.relation-form', compact('relation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Relation $relation
     * @return \Illuminate\Http\Response
     */
    public function update(RelationRequest $request, Relation $relation)
    {
        $relation->update($request->validated());

        return redirect()
            ->intended(route('relations.index'))
            ->with('toast_success', "Updated <b>'{$request->name}'</b>, Successfully!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Relation $relation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Relation $relation)
    {
        try {
            // Check if the rack has any associated delivery order
            if ($relation->delivery()->exists()) {
                return response()->json(['message' => 'Cannot Delete: Active Delivery Order found.'], 400);
            }

            // Check if the rack has any associated receive item
            if ($relation->receive()->exists()) {
                return response()->json(['message' => 'Cannot Delete: Active Receive Item found.'], 400);
            }

            $relation->delete();

            // Return success message if deletion is successful
            return response()->json(['message' => 'Relation deleted successfully!'], 200);
        } catch (\Exception $e) {
            return response()->json(['message' => 'Failed to delete relation. An error occurred while processing your request. Please try again later or contact support for assistance.'], 500);
        }
    }
}

resources/views/pages/relations/relation-form.blade.php
@extends('_layouts.base')

@section('title', 'Create Rack')

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-4">

            <x-form title='Relation' routePrefix='relations' :param='$relation ?? null'>

                {{-- Company Name input field --}}
                <x-input name='name' type='text' label='Company Name *' :bind='$component->model' />

                {{-- Company Address input field --}}
                <x-input-area name='address' type='textarea' label='Address' :bind='$component->model' />

                {{-- Company Type select field --}}
                <x-select-type-relation name='type' label="Company As ..." :bind='$component->model' />

                <!-- Settings Section -->
                <div class="d-flex align-items-center mb-3">
                    <i class="fas fa-cogs mr-2"></i> <!-- Font Awesome icon -->
                    <strong>Settings</strong>
                </div>

                <div class="custom-control custom-switch">
                    <input id="isDisplay" name="is_display" type="checkbox" class="custom-control-input switch-active" {{ $component->model && $component->model->is_display ? 'checked' : '' }}>
                    <label class="custom-control-label" for="isDisplay">Display PO / Part Number on Workorder</label>
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-primary mt-3">Save</button>
                </div>

            </x-form>
        </div>
    </div>
@endsection

resources/views/pages/relations/relation-index.blade.php
@extends('_layouts.base')

@section('title', 'Relation Company Data Master')

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-10">

            <h2> RELATION COMPANY DATA MASTER </h2>

            <div class="row pl-2 mb-3">
                <!-- Create new relation button -->
                <x-button id="buttonCreate" :url="route('relations.create')" class="bg-success btn-sm" icon="far fa-plus-square" label="Create" />
            </div>

            <!-- Relation table -->
            <x-card body-class='p-0'>
                <x-table id='tableRelation' />
            </x-card>
        </div>
    </div>
@endsection

@section('js')
    <script src="{{ URL::asset('js/tables/table-relation.js') }}"></script>
@endsection