routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\AdjustmentController;
use App\Http\Controllers\Web\DeliveryOrderController;
use App\Http\Controllers\Web\DeliveryScheduleController;
use App\Http\Controllers\Web\FormController;
use App\Http\Controllers\Web\FormulaController;
use App\Http\Controllers\Web\HistoryController;
use App\Http\Controllers\Web\JobCostController;
use App\Http\Controllers\Web\LoginController;
use App\Http\Controllers\Web\MachineCategoryController;
use App\Http\Controllers\Web\MachineController;
use App\Http\Controllers\Web\MachineProcessTypeController;
use App\Http\Controllers\Web\RelationController;
use App\Http\Controllers\Web\MaterialReleaseController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\ProductionOrderController;
use App\Http\Controllers\Web\SalesOrderController;
use App\Http\Controllers\Web\ProductResultController;
use App\Http\Controllers\Web\ReceiveItemController;
use App\Http\Controllers\Web\RoleController;
use App\Http\Controllers\Web\ScheduleController;
use App\Http\Controllers\Web\StocktakingController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Web\WarehouseController;
use App\Http\Controllers\Web\WarehouseRackController;
use App\Http\Controllers\Web\WorkOrderController;
use App\Http\Controllers\Api\ApiScheduleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route for user login
Route::get('/login', [LoginController::class, 'view'])->name('login');
Route::post('/login', [LoginController::class, 'attempt'])->name('attemptLogin');
Route::get('/logout', [LoginController::class, 'logout'])->middleware('auth')->name('logout');

// Routes inside middleware 'auth' require authentication
Route::middleware('auth')->group(function () {

    // Home route
    Route::view('/', 'pages.home')->name('home');

    Route::get('/schedule/production/ongoing', [ApiScheduleController::class, 'loadProductionOngoing'])->name('plan.production.ongoing');

    // Route for viewing product history
    Route::get('/products/{product}/history', [HistoryController::class, 'index']);

    // Resource routes for various controllers
    Route::resource('/adjustments', AdjustmentController::class);
    Route::resource('/deliveries', DeliveryOrderController::class);
    Route::resource('/formulas', FormulaController::class);
    Route::resource('/jobcosts', JobCostController::class);
    Route::resource('/machines', MachineController::class);
    Route::resource('/machine-category', MachineCategoryController::class);
    Route::resource('/machine-process-type', MachineProcessTypeController::class);
    Route::resource('/products', ProductController::class);
    Route::resource('/receives', ReceiveItemController::class);
    Route::resource('/relations', RelationController::class);
    Route::resource('/results', ProductResultController::class);
    Route::resource('/roles', RoleController::class);
    Route::resource('/users', UserController::class);
    Route::resource('/warehouses', WarehouseController::class);
    Route::resource('/warehouses.racks', WarehouseRackController::class);

    // Custom route for rendering work order form
    Route::get('/form/work-order/{formula}', [FormController::class, 'renderWorkOrderForm']);
    Route::get('/form/material-release/{lotNumber}', [FormController::class, 'renderMaterialReleaseForm']);
    Route::get('/form/production-result/{lotNumber}', [FormController::class, 'renderProductionResultForm']);

    // Route for exporting stocktaking data
    Route::get('/stocktaking/export', [StocktakingController::class, 'cutOff'])->name('stocktaking.export');
    Route::resource('/warehouses.racks', WarehouseRackController::class);

    // Route for viewing production schedule
    Route::get('/schedule/production', [ScheduleController::class, 'production'])->name("plan.production");
    Route::get('/schedule/production/preview', [ScheduleController::class, 'previewproduction'])->name("plan.production.preview");


    Route::get('/schedule/delivery', [ScheduleController::class, 'delivery'])->name("plan.delivery");

    Route::resource('salesorder', SalesOrderController::class)
        ->parameters(['salesorder' => 'order'])->except(['destroy', 'show']);

    Route::resource('productionorder', ProductionOrderController::class)
        ->parameters(['productionorder' => 'order'])->except(['create', 'update', 'destroy', 'show']);

    Route::get('productionorder/create/{product}', [ProductionOrderController::class, 'create'])
        ->name('productionorder.create');

    Route::put('productionorder/{product}', [ProductionOrderController::class, 'update'])
        ->name('productionorder.update');

    Route::resource('deliveryrequest', DeliveryScheduleController::class)->except('destroy', 'show');

    Route::resource('/workorders', WorkOrderController::class);

    Route::view('/warehouse-release', 'pages.material-release.material-release-form-warehouse');
    Route::resource('/releases', MaterialReleaseController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['username', 'password', 'attempt_clock', 'attempt_ip'];

    /**
     * Set the bycrypt password's first name.
     *
     * @param  string  $value
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['password'];
}

app/Http/Controllers/Web/UserController.php
<?php

namespace App\Http\Controllers\Web;

use \App\Models\User;
use \App\Http\Requests\UserRequest;
use \App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.users.user-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.users.user-form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        // Create a new user with the validated request data
        $user = User::create($request->validated());

        // Convert roles to integers if necessary
        $roleIds = array_map('intval', $request->roles);

        // Sync roles with the user
        $user->syncRoles($roleIds);

        // Redirect to the index page with success message
        return redirect()->route('users.index')->with('success', 'User created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('pages.users.user-form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        // Update user in the database
        $user->update($request->validated());

        // Convert roles to integers if necessary
        $roleIds = array_map('intval', $request->roles);

        // Sync roles with the user
        $user->syncRoles($roleIds);

        // Redirect to the users index page with success message
        return redirect()->route('users.index')->with('toast_success', 'User updated successfully!');
    }
}

resources/views/pages/users/user-form.blade.php
@extends('_layouts.base')

@section('title', 'User Management')

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-6">
            <x-form title="User" routePrefix="users" :param='$user ?? null'>
                @csrf {{-- Menyertakan token CSRF --}}

                <div class="row">  
                    <div class="col-8">  
                        {{-- Username input field --}}  
                        <x-input name='username' label='Username' :bind='$component->model' placeholder="Input New Username..." required />  
  
                        {{-- User role select field --}}  
                        <x-select name='roles[]' label='Select Roles' class='roles' multiple="multiple" :bind='$component->model' placeholder="Select roles..." />  
                    </div>  
                    <div class="col-4">  
                        {{-- Password input field --}}  
                        <x-input type='password' name='password' label='Password' placeholder='******' required />  
  
                        {{-- Password confirmation input field --}}  
                        <x-input type='password' name='password_confirmation' label='Password Confirmation' placeholder='******' required />  
                    </div>  
                </div>  
  
                {{-- Save button --}}  
                <div class="text-right">  
                    <button type="submit" class="btn btn-primary">Save</button>  
                </div>
            </x-form>
        </div>
    </div>
@endsection

@section('js')
    <script src="{{ URL::asset('js/utils/select2-utils.js') }}"></script>
@endsection

resources/views/pages/users/user-index.blade.php
@extends('_layouts.base')  
  
@section('title', 'Users Management')  
  
@section('content')  
    <div class="row d-flex justify-content-center">  
        <div class="col-11">  
  
            {{-- Header --}}  
            <h2> USER MANAGEMENT </h2>  
  
            {{-- Tools --}}  
            <div class="row d-flex justify-content-between">  
  
                {{-- Create button --}}  
                <div class="col-4 pl-2 mb-3">  
                    <x-button id="btn_create" :url="route('users.create')" class="btn btn-success" icon="far fa-plus-square" label="Create" />  
                </div>  
  
            </div>  
  
            <!-- User table -->  
            <x-card body-class='p-0'>  
                <x-table id='tableUser' />  
            </x-card>  
        </div>  
    </div>  
@endsection  
  
@section('js')  
    <script src="{{ URL::asset('js/tables/table-user.js') }}"></script>  
@endsection  